GET http://localhost:5000/books
Content-Type: application/json

###

POST http://localhost:5000/books
Content-Type: application/json

###

POST http://localhost:5000/books
Content-Type: application/json
Authorisation: auth_required

###

POST http://localhost:5000/books
Content-Type: application/json
Authorisation: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im15bmFtZSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjY3MDQxNDk4fQ.yi72LUzM-oE9GBstwPbkdkPyxX1bDGQAIryitSPXtS4

###

POST http://localhost:5000/books
Content-Type: application/json
Authorisation: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlNreXBybyIsInJvbGUiOiJhZG1pbiJ9.fMPkh9GNQMlLRxO0PmvCjUPPwX0t4CM5Wk4ATt35mNY
